# Plying with Pandas

Inspiration and some of the parts came from: Python Data Science [GitHub repository](https://github.com/jakevdp/PythonDataScienceHandbook/tree/master), [MIT License](https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/LICENSE-CODE) and [Introduction to Pandas](https://colab.research.google.com/notebooks/mlcc/intro_to_pandas.ipynb) by Google, [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)

needed packages:
 * pandas
 * numpy

support package
 * seaborn (load dataset titanic from seaborn package)
 * pivottablejs (for more easy pivot tables and fast simple visualization)
 * watermark (documenting version of packages)

In [32]:
#!pip install pandas
#!pip install numpy
#!pip install seaborn
!pip install watermark
#!pip install pivottablejs

Collecting watermark
  Downloading watermark-2.4.3-py2.py3-none-any.whl (7.6 kB)
Requirement already satisfied: ipython>=6.0 in /usr/local/lib/python3.10/dist-packages (from watermark) (7.34.0)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.10/dist-packages (from watermark) (6.8.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from watermark) (67.7.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=1.4->watermark) (3.16.2)
Collecting jedi>=0.16 (from ipython>=6.0->watermark)
  Downloading jedi-0.19.0-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.3 MB/s eta 0:00:00
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (3.0.39)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.0->watermark) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.0->watermark) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.0->watermark) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.0->watermark) (0.2.6)
Installing collected packages: jedi, watermark
Successfully installed jedi-0.19.0 watermark-2.4.3

## Intro to pandas

[*pandas*](http://pandas.pydata.org/) is a column-oriented data analysis API. It's a great tool for handling and analyzing input data, and many ML frameworks support *pandas* data structures as inputs.
Although a comprehensive introduction to the *pandas* API would span many pages, the core concepts are fairly straightforward, and we'll present them below. For a more complete reference, the [*pandas* docs site](http://pandas.pydata.org/pandas-docs/stable/index.html) contains extensive documentation and many tutorials.

## Learning Objectives:

 * Gain an introduction to the *DataFrame* and *Series* data structures of the pandas library

 * Import CSV data into a pandas *DataFrame*

 * Access and manipulate data within a *DataFrame* and *Series*

 * Export *DataFrame* to CSV
---
 * operations
  * selection
  * filtering
  * concat
  * NaNs
---
 * descriptive statistics/EDA
 * corr matrix
---
 * Simple plotting from *DataFrame*

 * Pivot tables

# Basic Concepts

The following line imports the *pandas* API and prints the API version:

In [33]:
from __future__ import print_function

import pandas as pd
pd.__version__

'1.5.3'

But most of the time, you load an entire file into a `DataFrame`. The following example loads a file with California housing data. Run the following cell to load the data and create feature definitions:

In [34]:
california_housing_dataframe = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")
california_housing_dataframe.head()
#california_housing_dataframe.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

If you need to take a peak to documentation, there is always fast way to use **?** after function. (For example if your columns are divided by ";" because marks "," decimal point as we do in Czech)

## Creating subsets

In [35]:
d1Area = california_housing_dataframe[['population','households','median_income']]
d2Area=d1Area;

## Filtering

codebooks etc.

In [36]:
d1Area_mask = d1Area.population > 1000
d1Area[d1Area_mask]

       population  households  median_income
0          1015.0       472.0         1.4936
1          1129.0       463.0         1.8200
6          1841.0       633.0         2.6768
8          3134.0      1056.0         2.1782
10         2434.0       824.0         2.6797
...           ...         ...            ...
16991      1343.0       479.0         2.4805
16993      1152.0       435.0         3.0806
16996      1194.0       465.0         2.5179
16997      1244.0       456.0         3.0313
16998      1298.0       478.0         1.9797

[10299 rows x 3 columns]

Alternatives

In [37]:
d1Area_mask = d1Area['population'] > 1000
d1Area[d1Area.population > 1000]

       population  households  median_income
0          1015.0       472.0         1.4936
1          1129.0       463.0         1.8200
6          1841.0       633.0         2.6768
8          3134.0      1056.0         2.1782
10         2434.0       824.0         2.6797
...           ...         ...            ...
16991      1343.0       479.0         2.4805
16993      1152.0       435.0         3.0806
16996      1194.0       465.0         2.5179
16997      1244.0       456.0         3.0313
16998      1298.0       478.0         1.9797

[10299 rows x 3 columns]

## Concat

Take 500 random samples from `d1Area` and `d2Area` and concatenete them.

In [38]:
data1=d1Area.sample(n=500, random_state=1)
data1['Label']='Data1'

data2=d2Area.sample(n=500, random_state=1)
data2['Label']='Data2'

resultOut = pd.concat([data1, data2])

In [39]:
data1=data1[['Label','population','households','median_income']]
data1.head()

       Label  population  households  median_income
4752   Data1      2621.0       661.0         6.2427
13348  Data1      1043.0       351.0         6.2048
13459  Data1       619.0       231.0         4.6304
6691   Data1       634.0       261.0         1.6406
12750  Data1      3060.0      1060.0         5.3064

In [40]:
data2=data2[['Label','population','households','median_income']]
data2.head()

       Label  population  households  median_income
4752   Data2      2621.0       661.0         6.2427
13348  Data2      1043.0       351.0         6.2048
13459  Data2       619.0       231.0         4.6304
6691   Data2       634.0       261.0         1.6406
12750  Data2      3060.0      1060.0         5.3064

## NaNs

`DataFrame` objects can be created by passing a `dict` mapping `string` column names to their respective `Series`. If the `Series` don't match in length, missing values are filled with special [NA/NaN](http://pandas.pydata.org/pandas-docs/stable/missing_data.html) values. We cannot assume what these values are, because that would distort th results. So we need to deal with these NaNs values.

We can test the missing values using `isnull()` function.

We can work with one of the `seaborn` training datasets *Penguins*

In [41]:
import seaborn as sns

In [42]:
penguins = sns.load_dataset("penguins")

In [43]:
penguins.isnull()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

But it is more practical to test if there are any NaNs, than looking for it. We can use `.isnull().values.any()` approach.

In [44]:
penguins.isnull().values.any()

True

Or we can explore each column using `.isnull().sum()`.

In [45]:
penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

We will want to drop all rows with unknown entries with `.dropna()` function.

In [46]:
penguins_cleaned = penguins.dropna()
penguins_cleaned.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

**Watermark**

In [47]:
from watermark import watermark
watermark(iversions=True, globals_=globals())
print(watermark())
print(watermark(packages="watermark,numpy,pandas,seaborn,pivottablejs"))

Last updated: 2023-08-15T06:48:16.265023+00:00

Python implementation: CPython
Python version       : 3.10.12
IPython version      : 7.34.0

Compiler    : GCC 11.4.0
OS          : Linux
Release     : 5.15.109+
Machine     : x86_64
Processor   : x86_64
CPU cores   : 2
Architecture: 64bit

watermark   : 2.4.3
numpy       : 1.23.5
pandas      : 1.5.3
seaborn     : 0.12.2
pivottablejs: not installed